= AsciiDoc Syntax Trail
Puneet Khamborkar <khamborkarpunit@gmail.com>
:version-label: Version 1.0
:homepage: https://github.com/PuneetKhamborkar/Web-Development
:toc:

Paragraph is important. A paragraph is required.

A line is needed.

A literal paragraph
git status


One or more consecutive lines

Roses are red, +
[[bookmark-e, last paragraph]]violets are blue.

[%hardbreaks]
A ruby is red.
Java is black.

[.lead]
This is what needs to be done.

It is *strong*

This is _not strong_

What about this '*_one_*'

**C**reate, **D**elete

fan__freakin__tastic

Beatle**__mania__**

Mark my words #automation is essential#

##Mark##up my words ##automation is essential##

Where are all the [.underline]#problems#

A [.myrole]#custom role# must be fulfilled by the theme.

^super^script

~super~script

"double curved quotes"

'single curved quotes'

[[bookmark-b]]A ``std::vector```'s size is the number of item it contains.

All of the [.line-through]#childrens`'# "Puneet"
123 `'00s.
s
[.underline]###my name is not Puneet###


anchor:bookmark-d[]^Khamborkar^Puneet~Suresh~

=== Links
Hi lover

[discrete]
==== I an a heading!



https://google.com[google] - automatic!


[#bookmark-c]#khamborkarpunit@gmail.com#

mailto:khamborkarpunit@gmail.com[connect with me]

https://www.google.com[Visit Google, role=external, window=_blank]

https://www.google.com[Visit Google^]

link:++https://www.google.com/search?q=vale&sca_esv=7c7b298578be5db7++[URL with characters]

link:antora-playbook.yml[antora]

link:../Boilerplate.html[Timepass]

refer to xref:trial2.adoc#file-masti-2[link section] on this document







